name: meraapss
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  # Menggunakan versi Dart SDK yang lebih fleksibel dan stabil
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # TAMBAHKAN DI SINI, dengan indentasi yang benar
  google_fonts: ^6.3.1 

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/quotidie.png
  # Hapus bagian 'assets:' yang salah jika tidak ada aset lokal yang digunakan.